config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'series#index'
  get '/search' => 'series#search'
  get '/personaje' => 'series#personajes'
  get '/series' => 'series#encontrar_series', as: :encontrar_series
  get '/episodes' => 'series#episodes'
  get '/episodeinfo' => 'series#episodeinfo'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
    
    def index
        encontrar_series()
    end
  
    def encontrar_series
        @episodes = find_all_episodes
        @series = []
        @seasons_serie = {}
        for e in @episodes
            serie = e['series']
            @series.append(serie) if not @series.include?(serie)
        end

        

        for serie in @series
            @seasons = []
            for e in @episodes
                temp = e['season']
                serie_e = e['series']
                if !@seasons.include?(temp) && serie_e == serie
                    @seasons.append(temp)
                end
            end
            @seasons_serie[serie] = @seasons
        end
        
    end

    def temporadas
        @temporadas = find_episodes_serie(params[:serie])
        @seasons = []
        for e in @temporadas
            temp = e['season']
            @seasons.append(temp) if not @seasons.include?(temp)
        end
    end

    def search
        offset = 0
        @personas = []
      @nuevos = find_person(params[:person], offset)
      while not @nuevos.empty?
        @personas = @personas + @nuevos
        offset = offset + 10
        @nuevos = find_person(params[:person], offset)
      end
    end

    def personajes
        @personas = find_person(params[:personaje], 0)
        @personaje = @personas.first
        @citas = find_quotes(@personaje['name'])



    end

    def episodes
        @episodios = find_episodes_serie_season(params[:serie], params[:season])
        @temporada = params[:season]
        @epi_season = []
        for e in @episodios
            epi = e['season']
            @epi_season.append(e) if epi == @temporada
        end
    end
  
    private
    def request_api(url)
      response = Excon.get(
          url
      )
      return nil if response.status != 200
      JSON.parse(response.body)
    end
  
    def find_person(name, offset)
      request_api(
          "https://tarea-1-breaking-bad.herokuapp.com/api/characters?name=#{URI.encode(name)}&limit=10&offset=#{offset}"
      )
    end

    def find_all_episodes
        request_api(
            "https://tarea-1-breaking-bad.herokuapp.com/api/episodes"
        )
      end

    def find_episodes_serie(name)
    request_api(
        "https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=#{URI.encode(name)}"
    )
    end

    def find_episodes_serie_season(serie, season)
        
        request_api(
            "https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=#{URI.encode(serie)}&season=#{URI.encode(season)}"
        )
        end

    def find_quotes(name)
        request_api(
            "https://tarea-1-breaking-bad.herokuapp.com/api/quote?author=#{URI.encode(name)}"
        )
        end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%#= csrf_meta_tags %>
    <%#= csp_meta_tag %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Buscador de series</title>
    <script src="https://kit.fontawesome.com/15181efa86.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />
    <link rel="stylesheet" type="text/css" href="https://bulmatemplates.github.io/bulma-templates/css/ghost-blog.css">
  </head>

  <body>
  <section class="hero is-medium">
   <div class="hero-head">
      <div class="container">
        <nav class="navbar" role="navigation" aria-label="main navigation">

          <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
              <a class="navbar-item is-active" >
                Series
              </a>
            </div>

            <div class="navbar-end">
              <div class="navbar-item">
              <%= form_with(url: search_path, method: 'get', local: true) do %>
                <%= label_tag :person, 'Buscar personajes'%>
                <%= text_field_tag :person, nil, placeholder: 'Eg. Walter White', class: 'form-control' %>
              <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
            <% end %>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </div>

    <div class="hero-body">
      <div class="container has-text-centered">
              <img src="https://spoilertime.com/wp-content/uploads/2019/01/C24.jpg" width="590" height="350">

        <h2 class="subtitle">
          Buscador de series Breaking Bad & Better Call Saul
        </h2>
      </div>
    </div>

    </section>
  <section class="blog-posts">
    <div class="container">
      <div class="columns">
        <div class="column is-10 is-offset-1">
        
            <%= yield %>
            </div>
    </div>
    </div>
    </section>



          
          
  </body>
</html>

app/views/series/episodeinfo.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <% @episodio = params[:episode] %>
        <%= 'Titulo: '%><%=@episodio['title']%>
        <br>
        <%= 'Fecha de lanzamiento: '%><%= @episodio['air_date']%>
        <br>
        <%= 'Personajes:'%>
        <br>
        <% @episodio['characters'].each do |f| %>
                <%= link_to f, personaje_path(personaje: f) %>
                <br>
            <% end %>
        <br>

    
    </div>

  </div>
</div>

app/views/series/episodes.html.erb
<div class="columns is-multiline">

            <div class="column post is-6">
              <article class="columns is-multiline">
                <%# <div class="column is-12 post-img"> %>
                  <%# <img src="https://cdn.emk.dev/templates/post-img.png" alt="Featured Image"> %>
                <%# </div> %>
                <div class="column is-12 featured-content ">
                  <h1 class="title post-title">Episodios de la temporada</h1>
                  <p class="post-excerpt">Accede a un episodios para ver su información.</p>
                  <br>
                  <table>
                  <% @epi_season.each do |f| %>
                  <tr>
                  <th>
                  <%= link_to f['title'], episodeinfo_path(episode: f)%>
                  </tr>
                  </th>
              <% end %>
              </table>


                  
                  <br>
                  
                </div>
              </article>
            </div>
</div>

app/views/series/index.html.erb
          <div class="columns is-multiline">

<% @series.each do |f| %>
            <div class="column post is-6">
              <article class="columns is-multiline">
                <%# <div class="column is-12 post-img"> %>
                  <%# <img src="https://cdn.emk.dev/templates/post-img.png" alt="Featured Image"> %>
                <%# </div> %>
                <div class="column is-12 featured-content ">
                  <h3 class="heading post-category">Serie:</h3>
                  <h1 class="title post-title"><%= f %></h1>
                  <p class="post-excerpt">Accede a una temporada para ver sus episodios.</p>
                  <br>


                  <% @seasons_serie[f].each do |g| %>
                    <%= link_to "Temporada #{g}", episodes_path(serie: f, season: g) %>
                    <br>
                <% end %>
                  <br>
                  <%#= link_to 'Temporadas', temporadas_path(serie: f), class: "button is-primary"%>
                  
                </div>
              </article>
            </div>

                        <%#= link_to f, temporadas_path(serie: f)%>
                        <%# <br> %>
                    <% end %>

</div>

app/views/series/personajes.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <h4>Información del personaje</h4>
      <figure width="100"
                    height="100">
              <%=image_tag(@personaje['img'], :size => "260x180") %>

            </figure>
        <%= 'Nombre: '%><%=@personaje['name']%>
        <br>
        <%= 'Ocupacion:'%>
        <br>
        <% @personaje['occupation'].each do |f| %>
                <%= f%>
                <br>
            <% end %>
        <br>
        <%= 'Estado: '%><%= @personaje['status']%>
        <br>
        <%= 'Nickname: '%><%= @personaje['nickname']%>
        <br>
        <%= 'Temporadas que aparece en Breaking Bad:'%>
        <br>
        <% @personaje['appearance'].each do |f| %>
                <%= link_to f, episodes_path(serie: "Breaking Bad", season: f) %>
                <br>
            <% end %>
        <%# if !@personaje['better_call_saul'].respond_to?(:to_s) && !@personaje['better_call_saul'].empty?%>
        <%= 'Temporadas que aparece en Better Call Saul:'%>
        <br>
        <% @personaje['better_call_saul_appearance'].each do |f| %>
                <%= link_to f, episodes_path(serie: "Better Call Saul", season: f) %>
                <br>
            <% end %>
        <%# end %>
        <%= 'Interpretado por: '%><%=@personaje['portrayed']%>
        <br>
        <%= 'Citas:'%>
        <br>
        <% @citas.each do |f| %>
                <%= f['quote'] %>
                <br>
            <% end %>
    </div>

  </div>
</div>

app/views/series/search.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <h4>Resultados de la búsqueda</h4>
      <% if  !@personas.empty? %>
      <% @personas.each do |f| %>
            <%= link_to f['name'], personaje_path(personaje: f['name']) %>
            <br>
        <% end %>
        <% else%>
        <%= 'No existen personajes con ese nombre, intentalo nuevamente!' %>
        <% end %>
    
    
    </div>

  </div>
</div>